[build-system]
build-backend = "setuptools.build_meta"
requires = [ "setuptools>=62.4.0", "wheel" ]

[project]
authors = [ { email = "snotbane@pm.me", name = "Sebastian Weaver" } ]
classifiers = [
  "Intended Audience :: Developers",
  "Topic :: Software Development :: Compilers",
  "Topic :: Text Processing :: Linguistic",
  "Typing :: Typed",
]
description = "Injected sub-grammar for Penny strings"
keywords = [ "incremental", "parsing", "tree-sitter", "penny-dialog" ]
license.text = "Unlicense"
name = "tree-sitter-penny-dialog"
readme = "README.md"
requires-python = ">=3.10"
version = "0.1.0"

[project.urls]
Funding = ""
Homepage = "https://github.com/snotbane/tree-sitter-penny-dialog.git"

[project.optional-dependencies]
core = [ "tree-sitter~=0.24" ]

[tool.cibuildwheel]
build = "cp310-*"
build-frontend = "build"
