/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 47
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 45
#define ALIAS_COUNT 0
#define TOKEN_COUNT 26
#define EXTERNAL_TOKEN_COUNT 1
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym__pure_formal = 1,
  sym__informal_misc = 2,
  aux_sym_number_token1 = 3,
  aux_sym_number_token2 = 4,
  aux_sym_number_token3 = 5,
  aux_sym_number_token4 = 6,
  anon_sym_LBRACE = 7,
  aux_sym_translation_token1 = 8,
  anon_sym_RBRACE = 9,
  aux_sym_translation_content_token1 = 10,
  sym_translation_content_invalid = 11,
  aux_sym_path_token1 = 12,
  anon_sym_AT = 13,
  anon_sym_LT = 14,
  anon_sym_GT = 15,
  anon_sym_LT_SLASH = 16,
  aux_sym_fx_token1 = 17,
  aux_sym_fx_token2 = 18,
  aux_sym_fx_id_token1 = 19,
  sym_fx_sep = 20,
  sym_fx_arg = 21,
  aux_sym_escape_token1 = 22,
  anon_sym_LBRACK = 23,
  anon_sym_RBRACK = 24,
  sym_express_content = 25,
  sym_text = 26,
  sym_pure = 27,
  sym_informal = 28,
  sym_number = 29,
  sym_translation = 30,
  sym_translation_content = 31,
  sym_path = 32,
  sym__path_declaration = 33,
  sym__tag = 34,
  sym_tag_start = 35,
  sym_tag_end = 36,
  sym_fx = 37,
  sym_fx_id = 38,
  sym_fx_param = 39,
  sym_escape = 40,
  sym_express = 41,
  aux_sym_text_repeat1 = 42,
  aux_sym_tag_start_repeat1 = 43,
  aux_sym_tag_end_repeat1 = 44,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym__pure_formal] = "_pure_formal",
  [sym__informal_misc] = "_informal_misc",
  [aux_sym_number_token1] = "number_token1",
  [aux_sym_number_token2] = "number_token2",
  [aux_sym_number_token3] = "number_token3",
  [aux_sym_number_token4] = "number_token4",
  [anon_sym_LBRACE] = "{",
  [aux_sym_translation_token1] = "translation_token1",
  [anon_sym_RBRACE] = "}",
  [aux_sym_translation_content_token1] = "translation_content_token1",
  [sym_translation_content_invalid] = "translation_content_invalid",
  [aux_sym_path_token1] = "path_token1",
  [anon_sym_AT] = "special",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_LT_SLASH] = "</",
  [aux_sym_fx_token1] = "fx_token1",
  [aux_sym_fx_token2] = "fx_token2",
  [aux_sym_fx_id_token1] = "fx_id_token1",
  [sym_fx_sep] = "fx_sep",
  [sym_fx_arg] = "fx_arg",
  [aux_sym_escape_token1] = "escape_token1",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [sym_express_content] = "express_content",
  [sym_text] = "text",
  [sym_pure] = "pure",
  [sym_informal] = "informal",
  [sym_number] = "number",
  [sym_translation] = "translation",
  [sym_translation_content] = "translation_content",
  [sym_path] = "path",
  [sym__path_declaration] = "_path_declaration",
  [sym__tag] = "_tag",
  [sym_tag_start] = "tag_start",
  [sym_tag_end] = "tag_end",
  [sym_fx] = "fx",
  [sym_fx_id] = "fx_id",
  [sym_fx_param] = "fx_param",
  [sym_escape] = "escape",
  [sym_express] = "express",
  [aux_sym_text_repeat1] = "text_repeat1",
  [aux_sym_tag_start_repeat1] = "tag_start_repeat1",
  [aux_sym_tag_end_repeat1] = "tag_end_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym__pure_formal] = sym__pure_formal,
  [sym__informal_misc] = sym__informal_misc,
  [aux_sym_number_token1] = aux_sym_number_token1,
  [aux_sym_number_token2] = aux_sym_number_token2,
  [aux_sym_number_token3] = aux_sym_number_token3,
  [aux_sym_number_token4] = aux_sym_number_token4,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [aux_sym_translation_token1] = aux_sym_translation_token1,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [aux_sym_translation_content_token1] = aux_sym_translation_content_token1,
  [sym_translation_content_invalid] = sym_translation_content_invalid,
  [aux_sym_path_token1] = aux_sym_path_token1,
  [anon_sym_AT] = anon_sym_AT,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LT_SLASH] = anon_sym_LT_SLASH,
  [aux_sym_fx_token1] = aux_sym_fx_token1,
  [aux_sym_fx_token2] = aux_sym_fx_token2,
  [aux_sym_fx_id_token1] = aux_sym_fx_id_token1,
  [sym_fx_sep] = sym_fx_sep,
  [sym_fx_arg] = sym_fx_arg,
  [aux_sym_escape_token1] = aux_sym_escape_token1,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [sym_express_content] = sym_express_content,
  [sym_text] = sym_text,
  [sym_pure] = sym_pure,
  [sym_informal] = sym_informal,
  [sym_number] = sym_number,
  [sym_translation] = sym_translation,
  [sym_translation_content] = sym_translation_content,
  [sym_path] = sym_path,
  [sym__path_declaration] = sym__path_declaration,
  [sym__tag] = sym__tag,
  [sym_tag_start] = sym_tag_start,
  [sym_tag_end] = sym_tag_end,
  [sym_fx] = sym_fx,
  [sym_fx_id] = sym_fx_id,
  [sym_fx_param] = sym_fx_param,
  [sym_escape] = sym_escape,
  [sym_express] = sym_express,
  [aux_sym_text_repeat1] = aux_sym_text_repeat1,
  [aux_sym_tag_start_repeat1] = aux_sym_tag_start_repeat1,
  [aux_sym_tag_end_repeat1] = aux_sym_tag_end_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym__pure_formal] = {
    .visible = false,
    .named = true,
  },
  [sym__informal_misc] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_number_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_number_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_number_token3] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_number_token4] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_translation_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_translation_content_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_translation_content_invalid] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_path_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_SLASH] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_fx_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_fx_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_fx_id_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_fx_sep] = {
    .visible = true,
    .named = true,
  },
  [sym_fx_arg] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_escape_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_express_content] = {
    .visible = true,
    .named = true,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [sym_pure] = {
    .visible = true,
    .named = true,
  },
  [sym_informal] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_translation] = {
    .visible = true,
    .named = true,
  },
  [sym_translation_content] = {
    .visible = true,
    .named = true,
  },
  [sym_path] = {
    .visible = true,
    .named = true,
  },
  [sym__path_declaration] = {
    .visible = false,
    .named = true,
  },
  [sym__tag] = {
    .visible = false,
    .named = true,
  },
  [sym_tag_start] = {
    .visible = true,
    .named = true,
  },
  [sym_tag_end] = {
    .visible = true,
    .named = true,
  },
  [sym_fx] = {
    .visible = true,
    .named = true,
  },
  [sym_fx_id] = {
    .visible = true,
    .named = true,
  },
  [sym_fx_param] = {
    .visible = true,
    .named = true,
  },
  [sym_escape] = {
    .visible = true,
    .named = true,
  },
  [sym_express] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_text_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_tag_start_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_tag_end_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ACCEPT_TOKEN(aux_sym_translation_token1);
      if (eof) ADVANCE(9);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(19);
      END_STATE();
    case 1:
      if (lookahead == '.') ADVANCE(6);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(23);
      END_STATE();
    case 2:
      if (lookahead == '=') ADVANCE(29);
      if (lookahead == '>') ADVANCE(26);
      if (lookahead == ']') ADVANCE(35);
      if (lookahead == '|') ADVANCE(31);
      if (lookahead == '}') ADVANCE(20);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(28);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(30);
      END_STATE();
    case 3:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(15);
      END_STATE();
    case 4:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(17);
      END_STATE();
    case 5:
      if (lookahead == '-' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(22);
      END_STATE();
    case 6:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(23);
      END_STATE();
    case 7:
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '>' &&
          lookahead != '|') ADVANCE(32);
      END_STATE();
    case 8:
      if (eof) ADVANCE(9);
      if (lookahead == '.') ADVANCE(10);
      if (lookahead == '<') ADVANCE(25);
      if (lookahead == '@') ADVANCE(24);
      if (lookahead == '[') ADVANCE(34);
      if (lookahead == '\\') ADVANCE(13);
      if (lookahead == '{') ADVANCE(18);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(14);
      if (('#' <= lookahead && lookahead <= '&') ||
          lookahead == '*' ||
          lookahead == '+' ||
          lookahead == '/' ||
          lookahead == '=' ||
          lookahead == '>' ||
          (']' <= lookahead && lookahead <= '`') ||
          lookahead == '|' ||
          lookahead == '}') ADVANCE(12);
      if (lookahead != 0) ADVANCE(11);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(sym__pure_formal);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(16);
      if (lookahead != 0 &&
          (lookahead < '#' || '&' < lookahead) &&
          lookahead != '*' &&
          lookahead != '+' &&
          (lookahead < '/' || '9' < lookahead) &&
          (lookahead < '<' || '>' < lookahead) &&
          lookahead != '@' &&
          (lookahead < '[' || '`' < lookahead) &&
          (lookahead < '{' || '}' < lookahead)) ADVANCE(11);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(sym__pure_formal);
      if (lookahead != 0 &&
          (lookahead < '#' || '&' < lookahead) &&
          lookahead != '*' &&
          lookahead != '+' &&
          (lookahead < '/' || '9' < lookahead) &&
          (lookahead < '<' || '>' < lookahead) &&
          lookahead != '@' &&
          (lookahead < '[' || '`' < lookahead) &&
          (lookahead < '{' || '}' < lookahead)) ADVANCE(11);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym__informal_misc);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym__informal_misc);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(33);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(aux_sym_number_token1);
      if (lookahead == '.') ADVANCE(3);
      if (lookahead == ':') ADVANCE(4);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(14);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(aux_sym_number_token2);
      if (lookahead == '.' ||
          lookahead == ':') ADVANCE(4);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(15);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(aux_sym_number_token3);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(16);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(aux_sym_number_token4);
      if (lookahead == '.' ||
          lookahead == ':') ADVANCE(4);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(17);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(aux_sym_translation_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(19);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(aux_sym_translation_content_token1);
      if (lookahead == '-' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(22);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_translation_content_invalid);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(22);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(aux_sym_path_token1);
      if (lookahead == '.') ADVANCE(6);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(23);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '/') ADVANCE(27);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_LT_SLASH);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(aux_sym_fx_token1);
      if (lookahead == '=') ADVANCE(29);
      if (lookahead == '|') ADVANCE(31);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(28);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(aux_sym_fx_token2);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(29);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(aux_sym_fx_id_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(30);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_fx_sep);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(31);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_fx_arg);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '>' &&
          lookahead != '|') ADVANCE(32);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(aux_sym_escape_token1);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 8},
  [2] = {.lex_state = 8},
  [3] = {.lex_state = 8},
  [4] = {.lex_state = 8},
  [5] = {.lex_state = 8},
  [6] = {.lex_state = 8},
  [7] = {.lex_state = 8},
  [8] = {.lex_state = 8},
  [9] = {.lex_state = 8},
  [10] = {.lex_state = 8},
  [11] = {.lex_state = 8},
  [12] = {.lex_state = 8},
  [13] = {.lex_state = 8},
  [14] = {.lex_state = 8},
  [15] = {.lex_state = 8},
  [16] = {.lex_state = 8},
  [17] = {.lex_state = 2},
  [18] = {.lex_state = 2},
  [19] = {.lex_state = 2},
  [20] = {.lex_state = 2},
  [21] = {.lex_state = 5},
  [22] = {.lex_state = 2},
  [23] = {.lex_state = 2},
  [24] = {.lex_state = 2},
  [25] = {.lex_state = 2},
  [26] = {.lex_state = 2},
  [27] = {.lex_state = 2},
  [28] = {.lex_state = 2},
  [29] = {.lex_state = 2},
  [30] = {.lex_state = 2},
  [31] = {.lex_state = 2},
  [32] = {.lex_state = 2},
  [33] = {.lex_state = 2},
  [34] = {.lex_state = 2},
  [35] = {.lex_state = 19},
  [36] = {.lex_state = 0, .external_lex_state = 1},
  [37] = {.lex_state = 19},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 2},
  [40] = {.lex_state = 1},
  [41] = {.lex_state = 2},
  [42] = {.lex_state = 2},
  [43] = {.lex_state = 19},
  [44] = {.lex_state = 2},
  [45] = {.lex_state = 7},
  [46] = {.lex_state = 7},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [aux_sym_translation_token1] = ACTIONS(1),
    [aux_sym_fx_token1] = ACTIONS(1),
    [sym_express_content] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_text] = STATE(38),
    [sym_pure] = STATE(2),
    [sym_informal] = STATE(4),
    [sym_number] = STATE(5),
    [sym_translation] = STATE(2),
    [sym_path] = STATE(2),
    [sym__path_declaration] = STATE(40),
    [sym__tag] = STATE(2),
    [sym_tag_start] = STATE(2),
    [sym_tag_end] = STATE(2),
    [sym_escape] = STATE(2),
    [sym_express] = STATE(2),
    [aux_sym_text_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym__pure_formal] = ACTIONS(5),
    [sym__informal_misc] = ACTIONS(7),
    [aux_sym_number_token1] = ACTIONS(9),
    [aux_sym_number_token2] = ACTIONS(9),
    [aux_sym_number_token3] = ACTIONS(11),
    [aux_sym_number_token4] = ACTIONS(9),
    [anon_sym_LBRACE] = ACTIONS(13),
    [anon_sym_AT] = ACTIONS(15),
    [anon_sym_LT] = ACTIONS(17),
    [anon_sym_LT_SLASH] = ACTIONS(19),
    [aux_sym_escape_token1] = ACTIONS(21),
    [anon_sym_LBRACK] = ACTIONS(23),
  },
  [STATE(2)] = {
    [sym_pure] = STATE(3),
    [sym_informal] = STATE(4),
    [sym_number] = STATE(5),
    [sym_translation] = STATE(3),
    [sym_path] = STATE(3),
    [sym__path_declaration] = STATE(40),
    [sym__tag] = STATE(3),
    [sym_tag_start] = STATE(3),
    [sym_tag_end] = STATE(3),
    [sym_escape] = STATE(3),
    [sym_express] = STATE(3),
    [aux_sym_text_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(25),
    [sym__pure_formal] = ACTIONS(5),
    [sym__informal_misc] = ACTIONS(7),
    [aux_sym_number_token1] = ACTIONS(9),
    [aux_sym_number_token2] = ACTIONS(9),
    [aux_sym_number_token3] = ACTIONS(11),
    [aux_sym_number_token4] = ACTIONS(9),
    [anon_sym_LBRACE] = ACTIONS(13),
    [anon_sym_AT] = ACTIONS(15),
    [anon_sym_LT] = ACTIONS(17),
    [anon_sym_LT_SLASH] = ACTIONS(19),
    [aux_sym_escape_token1] = ACTIONS(21),
    [anon_sym_LBRACK] = ACTIONS(23),
  },
  [STATE(3)] = {
    [sym_pure] = STATE(3),
    [sym_informal] = STATE(4),
    [sym_number] = STATE(5),
    [sym_translation] = STATE(3),
    [sym_path] = STATE(3),
    [sym__path_declaration] = STATE(40),
    [sym__tag] = STATE(3),
    [sym_tag_start] = STATE(3),
    [sym_tag_end] = STATE(3),
    [sym_escape] = STATE(3),
    [sym_express] = STATE(3),
    [aux_sym_text_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(27),
    [sym__pure_formal] = ACTIONS(29),
    [sym__informal_misc] = ACTIONS(32),
    [aux_sym_number_token1] = ACTIONS(35),
    [aux_sym_number_token2] = ACTIONS(35),
    [aux_sym_number_token3] = ACTIONS(38),
    [aux_sym_number_token4] = ACTIONS(35),
    [anon_sym_LBRACE] = ACTIONS(41),
    [anon_sym_AT] = ACTIONS(44),
    [anon_sym_LT] = ACTIONS(47),
    [anon_sym_LT_SLASH] = ACTIONS(50),
    [aux_sym_escape_token1] = ACTIONS(53),
    [anon_sym_LBRACK] = ACTIONS(56),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 2,
    ACTIONS(61), 6,
      sym__pure_formal,
      sym__informal_misc,
      aux_sym_number_token1,
      aux_sym_number_token2,
      aux_sym_number_token4,
      anon_sym_LT,
    ACTIONS(59), 7,
      ts_builtin_sym_end,
      aux_sym_number_token3,
      anon_sym_LBRACE,
      anon_sym_AT,
      anon_sym_LT_SLASH,
      aux_sym_escape_token1,
      anon_sym_LBRACK,
  [18] = 2,
    ACTIONS(65), 6,
      sym__pure_formal,
      sym__informal_misc,
      aux_sym_number_token1,
      aux_sym_number_token2,
      aux_sym_number_token4,
      anon_sym_LT,
    ACTIONS(63), 7,
      ts_builtin_sym_end,
      aux_sym_number_token3,
      anon_sym_LBRACE,
      anon_sym_AT,
      anon_sym_LT_SLASH,
      aux_sym_escape_token1,
      anon_sym_LBRACK,
  [36] = 2,
    ACTIONS(69), 6,
      sym__pure_formal,
      sym__informal_misc,
      aux_sym_number_token1,
      aux_sym_number_token2,
      aux_sym_number_token4,
      anon_sym_LT,
    ACTIONS(67), 7,
      ts_builtin_sym_end,
      aux_sym_number_token3,
      anon_sym_LBRACE,
      anon_sym_AT,
      anon_sym_LT_SLASH,
      aux_sym_escape_token1,
      anon_sym_LBRACK,
  [54] = 2,
    ACTIONS(73), 6,
      sym__pure_formal,
      sym__informal_misc,
      aux_sym_number_token1,
      aux_sym_number_token2,
      aux_sym_number_token4,
      anon_sym_LT,
    ACTIONS(71), 7,
      ts_builtin_sym_end,
      aux_sym_number_token3,
      anon_sym_LBRACE,
      anon_sym_AT,
      anon_sym_LT_SLASH,
      aux_sym_escape_token1,
      anon_sym_LBRACK,
  [72] = 2,
    ACTIONS(77), 6,
      sym__pure_formal,
      sym__informal_misc,
      aux_sym_number_token1,
      aux_sym_number_token2,
      aux_sym_number_token4,
      anon_sym_LT,
    ACTIONS(75), 7,
      ts_builtin_sym_end,
      aux_sym_number_token3,
      anon_sym_LBRACE,
      anon_sym_AT,
      anon_sym_LT_SLASH,
      aux_sym_escape_token1,
      anon_sym_LBRACK,
  [90] = 2,
    ACTIONS(81), 6,
      sym__pure_formal,
      sym__informal_misc,
      aux_sym_number_token1,
      aux_sym_number_token2,
      aux_sym_number_token4,
      anon_sym_LT,
    ACTIONS(79), 7,
      ts_builtin_sym_end,
      aux_sym_number_token3,
      anon_sym_LBRACE,
      anon_sym_AT,
      anon_sym_LT_SLASH,
      aux_sym_escape_token1,
      anon_sym_LBRACK,
  [108] = 2,
    ACTIONS(85), 6,
      sym__pure_formal,
      sym__informal_misc,
      aux_sym_number_token1,
      aux_sym_number_token2,
      aux_sym_number_token4,
      anon_sym_LT,
    ACTIONS(83), 7,
      ts_builtin_sym_end,
      aux_sym_number_token3,
      anon_sym_LBRACE,
      anon_sym_AT,
      anon_sym_LT_SLASH,
      aux_sym_escape_token1,
      anon_sym_LBRACK,
  [126] = 2,
    ACTIONS(89), 6,
      sym__pure_formal,
      sym__informal_misc,
      aux_sym_number_token1,
      aux_sym_number_token2,
      aux_sym_number_token4,
      anon_sym_LT,
    ACTIONS(87), 7,
      ts_builtin_sym_end,
      aux_sym_number_token3,
      anon_sym_LBRACE,
      anon_sym_AT,
      anon_sym_LT_SLASH,
      aux_sym_escape_token1,
      anon_sym_LBRACK,
  [144] = 2,
    ACTIONS(93), 6,
      sym__pure_formal,
      sym__informal_misc,
      aux_sym_number_token1,
      aux_sym_number_token2,
      aux_sym_number_token4,
      anon_sym_LT,
    ACTIONS(91), 7,
      ts_builtin_sym_end,
      aux_sym_number_token3,
      anon_sym_LBRACE,
      anon_sym_AT,
      anon_sym_LT_SLASH,
      aux_sym_escape_token1,
      anon_sym_LBRACK,
  [162] = 2,
    ACTIONS(97), 6,
      sym__pure_formal,
      sym__informal_misc,
      aux_sym_number_token1,
      aux_sym_number_token2,
      aux_sym_number_token4,
      anon_sym_LT,
    ACTIONS(95), 7,
      ts_builtin_sym_end,
      aux_sym_number_token3,
      anon_sym_LBRACE,
      anon_sym_AT,
      anon_sym_LT_SLASH,
      aux_sym_escape_token1,
      anon_sym_LBRACK,
  [180] = 2,
    ACTIONS(101), 6,
      sym__pure_formal,
      sym__informal_misc,
      aux_sym_number_token1,
      aux_sym_number_token2,
      aux_sym_number_token4,
      anon_sym_LT,
    ACTIONS(99), 7,
      ts_builtin_sym_end,
      aux_sym_number_token3,
      anon_sym_LBRACE,
      anon_sym_AT,
      anon_sym_LT_SLASH,
      aux_sym_escape_token1,
      anon_sym_LBRACK,
  [198] = 2,
    ACTIONS(105), 6,
      sym__pure_formal,
      sym__informal_misc,
      aux_sym_number_token1,
      aux_sym_number_token2,
      aux_sym_number_token4,
      anon_sym_LT,
    ACTIONS(103), 7,
      ts_builtin_sym_end,
      aux_sym_number_token3,
      anon_sym_LBRACE,
      anon_sym_AT,
      anon_sym_LT_SLASH,
      aux_sym_escape_token1,
      anon_sym_LBRACK,
  [216] = 2,
    ACTIONS(109), 6,
      sym__pure_formal,
      sym__informal_misc,
      aux_sym_number_token1,
      aux_sym_number_token2,
      aux_sym_number_token4,
      anon_sym_LT,
    ACTIONS(107), 7,
      ts_builtin_sym_end,
      aux_sym_number_token3,
      anon_sym_LBRACE,
      anon_sym_AT,
      anon_sym_LT_SLASH,
      aux_sym_escape_token1,
      anon_sym_LBRACK,
  [234] = 4,
    ACTIONS(111), 1,
      anon_sym_GT,
    ACTIONS(113), 1,
      aux_sym_fx_id_token1,
    STATE(19), 1,
      sym_fx_id,
    STATE(22), 1,
      sym_fx,
  [247] = 2,
    ACTIONS(117), 1,
      aux_sym_fx_token1,
    ACTIONS(115), 3,
      anon_sym_GT,
      aux_sym_fx_token2,
      sym_fx_sep,
  [256] = 3,
    ACTIONS(121), 1,
      aux_sym_fx_token1,
    ACTIONS(123), 1,
      aux_sym_fx_token2,
    ACTIONS(119), 2,
      anon_sym_GT,
      sym_fx_sep,
  [267] = 3,
    ACTIONS(113), 1,
      aux_sym_fx_id_token1,
    ACTIONS(125), 1,
      anon_sym_GT,
    STATE(27), 1,
      sym_fx_id,
  [277] = 3,
    ACTIONS(127), 1,
      aux_sym_translation_content_token1,
    ACTIONS(129), 1,
      sym_translation_content_invalid,
    STATE(43), 1,
      sym_translation_content,
  [287] = 3,
    ACTIONS(131), 1,
      anon_sym_GT,
    ACTIONS(133), 1,
      sym_fx_sep,
    STATE(24), 1,
      aux_sym_tag_start_repeat1,
  [297] = 3,
    ACTIONS(113), 1,
      aux_sym_fx_id_token1,
    STATE(19), 1,
      sym_fx_id,
    STATE(29), 1,
      sym_fx,
  [307] = 3,
    ACTIONS(133), 1,
      sym_fx_sep,
    ACTIONS(135), 1,
      anon_sym_GT,
    STATE(26), 1,
      aux_sym_tag_start_repeat1,
  [317] = 3,
    ACTIONS(137), 1,
      anon_sym_GT,
    ACTIONS(139), 1,
      sym_fx_sep,
    STATE(28), 1,
      aux_sym_tag_end_repeat1,
  [327] = 3,
    ACTIONS(141), 1,
      anon_sym_GT,
    ACTIONS(143), 1,
      sym_fx_sep,
    STATE(26), 1,
      aux_sym_tag_start_repeat1,
  [337] = 3,
    ACTIONS(139), 1,
      sym_fx_sep,
    ACTIONS(146), 1,
      anon_sym_GT,
    STATE(25), 1,
      aux_sym_tag_end_repeat1,
  [347] = 3,
    ACTIONS(148), 1,
      anon_sym_GT,
    ACTIONS(150), 1,
      sym_fx_sep,
    STATE(28), 1,
      aux_sym_tag_end_repeat1,
  [357] = 1,
    ACTIONS(141), 2,
      anon_sym_GT,
      sym_fx_sep,
  [362] = 1,
    ACTIONS(148), 2,
      anon_sym_GT,
      sym_fx_sep,
  [367] = 2,
    ACTIONS(113), 1,
      aux_sym_fx_id_token1,
    STATE(30), 1,
      sym_fx_id,
  [374] = 1,
    ACTIONS(153), 2,
      anon_sym_GT,
      sym_fx_sep,
  [379] = 2,
    ACTIONS(155), 1,
      aux_sym_fx_id_token1,
    STATE(41), 1,
      sym_fx_param,
  [386] = 1,
    ACTIONS(157), 2,
      anon_sym_GT,
      sym_fx_sep,
  [391] = 1,
    ACTIONS(159), 1,
      aux_sym_translation_token1,
  [395] = 1,
    ACTIONS(161), 1,
      sym_express_content,
  [399] = 1,
    ACTIONS(163), 1,
      aux_sym_translation_token1,
  [403] = 1,
    ACTIONS(165), 1,
      ts_builtin_sym_end,
  [407] = 1,
    ACTIONS(167), 1,
      anon_sym_RBRACE,
  [411] = 1,
    ACTIONS(169), 1,
      aux_sym_path_token1,
  [415] = 1,
    ACTIONS(171), 1,
      aux_sym_fx_token2,
  [419] = 1,
    ACTIONS(173), 1,
      aux_sym_fx_token2,
  [423] = 1,
    ACTIONS(175), 1,
      aux_sym_translation_token1,
  [427] = 1,
    ACTIONS(177), 1,
      anon_sym_RBRACK,
  [431] = 1,
    ACTIONS(179), 1,
      sym_fx_arg,
  [435] = 1,
    ACTIONS(181), 1,
      sym_fx_arg,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(4)] = 0,
  [SMALL_STATE(5)] = 18,
  [SMALL_STATE(6)] = 36,
  [SMALL_STATE(7)] = 54,
  [SMALL_STATE(8)] = 72,
  [SMALL_STATE(9)] = 90,
  [SMALL_STATE(10)] = 108,
  [SMALL_STATE(11)] = 126,
  [SMALL_STATE(12)] = 144,
  [SMALL_STATE(13)] = 162,
  [SMALL_STATE(14)] = 180,
  [SMALL_STATE(15)] = 198,
  [SMALL_STATE(16)] = 216,
  [SMALL_STATE(17)] = 234,
  [SMALL_STATE(18)] = 247,
  [SMALL_STATE(19)] = 256,
  [SMALL_STATE(20)] = 267,
  [SMALL_STATE(21)] = 277,
  [SMALL_STATE(22)] = 287,
  [SMALL_STATE(23)] = 297,
  [SMALL_STATE(24)] = 307,
  [SMALL_STATE(25)] = 317,
  [SMALL_STATE(26)] = 327,
  [SMALL_STATE(27)] = 337,
  [SMALL_STATE(28)] = 347,
  [SMALL_STATE(29)] = 357,
  [SMALL_STATE(30)] = 362,
  [SMALL_STATE(31)] = 367,
  [SMALL_STATE(32)] = 374,
  [SMALL_STATE(33)] = 379,
  [SMALL_STATE(34)] = 386,
  [SMALL_STATE(35)] = 391,
  [SMALL_STATE(36)] = 395,
  [SMALL_STATE(37)] = 399,
  [SMALL_STATE(38)] = 403,
  [SMALL_STATE(39)] = 407,
  [SMALL_STATE(40)] = 411,
  [SMALL_STATE(41)] = 415,
  [SMALL_STATE(42)] = 419,
  [SMALL_STATE(43)] = 423,
  [SMALL_STATE(44)] = 427,
  [SMALL_STATE(45)] = 431,
  [SMALL_STATE(46)] = 435,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_text, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_text, 1, 0, 0),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_text_repeat1, 2, 0, 0),
  [29] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_text_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [32] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_text_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [35] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_text_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [38] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_text_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [41] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_text_repeat1, 2, 0, 0), SHIFT_REPEAT(37),
  [44] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_text_repeat1, 2, 0, 0), SHIFT_REPEAT(40),
  [47] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_text_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [50] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_text_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [53] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_text_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [56] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_text_repeat1, 2, 0, 0), SHIFT_REPEAT(36),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pure, 1, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_pure, 1, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_informal, 1, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_informal, 1, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_escape, 1, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_escape, 1, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag_start, 2, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag_start, 2, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_number, 1, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_number, 1, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag_end, 2, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag_end, 2, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag_end, 4, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag_end, 4, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag_start, 3, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag_start, 3, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_path, 2, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_path, 2, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag_start, 4, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag_start, 4, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_express, 3, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_express, 3, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag_end, 3, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag_end, 3, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_translation, 5, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_translation, 5, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fx_id, 1, 0, 0),
  [117] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_fx_id, 1, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fx, 1, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [127] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [129] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_tag_start_repeat1, 2, 0, 0),
  [143] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tag_start_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_tag_end_repeat1, 2, 0, 0),
  [150] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tag_end_repeat1, 2, 0, 0), SHIFT_REPEAT(31),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fx, 3, 0, 0),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fx, 5, 0, 0),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_translation_content, 1, 0, 0),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [165] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fx_param, 1, 0, 0),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token_express_content = 0,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token_express_content] = sym_express_content,
};

static const bool ts_external_scanner_states[2][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token_express_content] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_penny_dialog_external_scanner_create(void);
void tree_sitter_penny_dialog_external_scanner_destroy(void *);
bool tree_sitter_penny_dialog_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_penny_dialog_external_scanner_serialize(void *, char *);
void tree_sitter_penny_dialog_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_penny_dialog(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_penny_dialog_external_scanner_create,
      tree_sitter_penny_dialog_external_scanner_destroy,
      tree_sitter_penny_dialog_external_scanner_scan,
      tree_sitter_penny_dialog_external_scanner_serialize,
      tree_sitter_penny_dialog_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
    .name = "penny_dialog",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
