/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 86
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 50
#define ALIAS_COUNT 0
#define TOKEN_COUNT 30
#define EXTERNAL_TOKEN_COUNT 1
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_BQUOTE = 1,
  anon_sym_GT = 2,
  aux_sym_escape_sequence_token1 = 3,
  aux_sym_number_token1 = 4,
  aux_sym_number_token2 = 5,
  aux_sym_number_token3 = 6,
  aux_sym_number_token4 = 7,
  sym__formal = 8,
  sym__informal_misc = 9,
  anon_sym_LBRACE = 10,
  anon_sym_RBRACE = 11,
  anon_sym_AT = 12,
  aux_sym_path_token1 = 13,
  sym_identifier = 14,
  anon_sym_LBRACK = 15,
  anon_sym_RBRACK = 16,
  aux_sym_lang_token1 = 17,
  sym_lang_invalid = 18,
  anon_sym_LT = 19,
  anon_sym_PIPE = 20,
  anon_sym_LT_SLASH = 21,
  anon_sym_EQ = 22,
  aux_sym_arg_value_token1 = 23,
  anon_sym_SQUOTE = 24,
  aux_sym__quoted_string_token1 = 25,
  anon_sym_DQUOTE = 26,
  aux_sym__quoted_string_token2 = 27,
  aux_sym__quoted_string_token3 = 28,
  sym_expression_content = 29,
  sym_text = 30,
  aux_sym__contents = 31,
  sym_escape_sequence = 32,
  sym_number = 33,
  sym_pure = 34,
  sym_informal = 35,
  sym_expression = 36,
  sym_path = 37,
  sym_translation_marker = 38,
  sym_lang = 39,
  sym__tag = 40,
  sym_tag_start = 41,
  sym_tag_end = 42,
  sym_decor = 43,
  sym_arg = 44,
  sym_arg_value = 45,
  sym__quoted_string = 46,
  aux_sym_tag_start_repeat1 = 47,
  aux_sym_tag_end_repeat1 = 48,
  aux_sym_decor_repeat1 = 49,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_BQUOTE] = "`",
  [anon_sym_GT] = ">",
  [aux_sym_escape_sequence_token1] = "escape_sequence_token1",
  [aux_sym_number_token1] = "number_token1",
  [aux_sym_number_token2] = "number_token2",
  [aux_sym_number_token3] = "number_token3",
  [aux_sym_number_token4] = "number_token4",
  [sym__formal] = "_formal",
  [sym__informal_misc] = "_informal_misc",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_AT] = "@",
  [aux_sym_path_token1] = "path_token1",
  [sym_identifier] = "identifier",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [aux_sym_lang_token1] = "lang_token1",
  [sym_lang_invalid] = "lang_invalid",
  [anon_sym_LT] = "<",
  [anon_sym_PIPE] = "|",
  [anon_sym_LT_SLASH] = "</",
  [anon_sym_EQ] = "=",
  [aux_sym_arg_value_token1] = "arg_value_token1",
  [anon_sym_SQUOTE] = "'",
  [aux_sym__quoted_string_token1] = "_quoted_string_token1",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym__quoted_string_token2] = "_quoted_string_token2",
  [aux_sym__quoted_string_token3] = "_quoted_string_token3",
  [sym_expression_content] = "expression_content",
  [sym_text] = "text",
  [aux_sym__contents] = "_contents",
  [sym_escape_sequence] = "escape_sequence",
  [sym_number] = "number",
  [sym_pure] = "pure",
  [sym_informal] = "informal",
  [sym_expression] = "expression",
  [sym_path] = "path",
  [sym_translation_marker] = "translation_marker",
  [sym_lang] = "lang",
  [sym__tag] = "_tag",
  [sym_tag_start] = "tag_start",
  [sym_tag_end] = "tag_end",
  [sym_decor] = "decor",
  [sym_arg] = "arg",
  [sym_arg_value] = "arg_value",
  [sym__quoted_string] = "_quoted_string",
  [aux_sym_tag_start_repeat1] = "tag_start_repeat1",
  [aux_sym_tag_end_repeat1] = "tag_end_repeat1",
  [aux_sym_decor_repeat1] = "decor_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_BQUOTE] = anon_sym_BQUOTE,
  [anon_sym_GT] = anon_sym_GT,
  [aux_sym_escape_sequence_token1] = aux_sym_escape_sequence_token1,
  [aux_sym_number_token1] = aux_sym_number_token1,
  [aux_sym_number_token2] = aux_sym_number_token2,
  [aux_sym_number_token3] = aux_sym_number_token3,
  [aux_sym_number_token4] = aux_sym_number_token4,
  [sym__formal] = sym__formal,
  [sym__informal_misc] = sym__informal_misc,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_AT] = anon_sym_AT,
  [aux_sym_path_token1] = aux_sym_path_token1,
  [sym_identifier] = sym_identifier,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [aux_sym_lang_token1] = aux_sym_lang_token1,
  [sym_lang_invalid] = sym_lang_invalid,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [anon_sym_LT_SLASH] = anon_sym_LT_SLASH,
  [anon_sym_EQ] = anon_sym_EQ,
  [aux_sym_arg_value_token1] = aux_sym_arg_value_token1,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym__quoted_string_token1] = aux_sym__quoted_string_token1,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym__quoted_string_token2] = aux_sym__quoted_string_token2,
  [aux_sym__quoted_string_token3] = aux_sym__quoted_string_token3,
  [sym_expression_content] = sym_expression_content,
  [sym_text] = sym_text,
  [aux_sym__contents] = aux_sym__contents,
  [sym_escape_sequence] = sym_escape_sequence,
  [sym_number] = sym_number,
  [sym_pure] = sym_pure,
  [sym_informal] = sym_informal,
  [sym_expression] = sym_expression,
  [sym_path] = sym_path,
  [sym_translation_marker] = sym_translation_marker,
  [sym_lang] = sym_lang,
  [sym__tag] = sym__tag,
  [sym_tag_start] = sym_tag_start,
  [sym_tag_end] = sym_tag_end,
  [sym_decor] = sym_decor,
  [sym_arg] = sym_arg,
  [sym_arg_value] = sym_arg_value,
  [sym__quoted_string] = sym__quoted_string,
  [aux_sym_tag_start_repeat1] = aux_sym_tag_start_repeat1,
  [aux_sym_tag_end_repeat1] = aux_sym_tag_end_repeat1,
  [aux_sym_decor_repeat1] = aux_sym_decor_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_BQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_escape_sequence_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_number_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_number_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_number_token3] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_number_token4] = {
    .visible = false,
    .named = false,
  },
  [sym__formal] = {
    .visible = false,
    .named = true,
  },
  [sym__informal_misc] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_path_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_lang_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_lang_invalid] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_arg_value_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__quoted_string_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__quoted_string_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__quoted_string_token3] = {
    .visible = false,
    .named = false,
  },
  [sym_expression_content] = {
    .visible = true,
    .named = true,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__contents] = {
    .visible = false,
    .named = false,
  },
  [sym_escape_sequence] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_pure] = {
    .visible = true,
    .named = true,
  },
  [sym_informal] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_path] = {
    .visible = true,
    .named = true,
  },
  [sym_translation_marker] = {
    .visible = true,
    .named = true,
  },
  [sym_lang] = {
    .visible = true,
    .named = true,
  },
  [sym__tag] = {
    .visible = false,
    .named = true,
  },
  [sym_tag_start] = {
    .visible = true,
    .named = true,
  },
  [sym_tag_end] = {
    .visible = true,
    .named = true,
  },
  [sym_decor] = {
    .visible = true,
    .named = true,
  },
  [sym_arg] = {
    .visible = true,
    .named = true,
  },
  [sym_arg_value] = {
    .visible = true,
    .named = true,
  },
  [sym__quoted_string] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_tag_start_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_tag_end_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_decor_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 5,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 9,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 10,
  [24] = 14,
  [25] = 11,
  [26] = 12,
  [27] = 15,
  [28] = 21,
  [29] = 13,
  [30] = 16,
  [31] = 19,
  [32] = 18,
  [33] = 20,
  [34] = 22,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 40,
  [42] = 11,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 13,
  [54] = 44,
  [55] = 49,
  [56] = 50,
  [57] = 51,
  [58] = 46,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 60,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 69,
  [76] = 65,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 69,
  [82] = 78,
  [83] = 79,
  [84] = 78,
  [85] = 79,
};

static const TSCharacterRange aux_sym_arg_value_token1_character_set_1[] = {
  {0, 0x08}, {0x0e, 0x1f}, {'!', '!'}, {'#', '&'}, {'(', '='}, {'?', '?'}, {'A', '_'}, {'a', 'z'},
  {'~', 0x10ffff},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(12);
      ADVANCE_MAP(
        '"', 44,
        '\'', 41,
        '.', 6,
        '<', 36,
        '=', 39,
        '>', 14,
        '@', 27,
        '[', 30,
        '\\', 24,
        ']', 31,
        '`', 13,
        '{', 25,
        '|', 37,
        '}', 26,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('#' <= lookahead && lookahead <= '&') ||
          lookahead == '*' ||
          lookahead == '+' ||
          lookahead == '/' ||
          lookahead == '^' ||
          lookahead == '_') ADVANCE(23);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(16);
      if (lookahead == '-' ||
          ('A' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '"', 44,
        '\'', 41,
        '>', 14,
        '@', 27,
        '`', 13,
        '{', 25,
        '|', 37,
        '}', 26,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (lookahead != 0) ADVANCE(40);
      END_STATE();
    case 2:
      if (lookahead == '.') ADVANCE(21);
      if (lookahead == '<') ADVANCE(36);
      if (lookahead == '@') ADVANCE(27);
      if (lookahead == '[') ADVANCE(30);
      if (lookahead == '\\') ADVANCE(24);
      if (lookahead == '`') ADVANCE(13);
      if (lookahead == '{') ADVANCE(25);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(20);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(16);
      if (('#' <= lookahead && lookahead <= '&') ||
          lookahead == '*' ||
          lookahead == '+' ||
          lookahead == '/' ||
          lookahead == '=' ||
          lookahead == '>' ||
          (']' <= lookahead && lookahead <= '_') ||
          lookahead == '|' ||
          lookahead == '}') ADVANCE(23);
      if (lookahead != 0) ADVANCE(22);
      END_STATE();
    case 3:
      if (lookahead == '.') ADVANCE(9);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 4:
      if (lookahead == '=') ADVANCE(39);
      if (lookahead == '>') ADVANCE(14);
      if (lookahead == ']') ADVANCE(31);
      if (lookahead == '|') ADVANCE(37);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(4);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(29);
      END_STATE();
    case 5:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(34);
      if (lookahead == '-' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      if (lookahead != 0 &&
          lookahead != ']') ADVANCE(35);
      END_STATE();
    case 6:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(18);
      END_STATE();
    case 7:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(17);
      END_STATE();
    case 8:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(19);
      END_STATE();
    case 9:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 10:
      if (eof) ADVANCE(12);
      ADVANCE_MAP(
        '.', 21,
        '<', 36,
        '>', 14,
        '@', 27,
        '[', 30,
        '\\', 24,
        '`', 13,
        '{', 25,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(20);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(16);
      if (('#' <= lookahead && lookahead <= '&') ||
          lookahead == '*' ||
          lookahead == '+' ||
          lookahead == '/' ||
          lookahead == '=' ||
          (']' <= lookahead && lookahead <= '_') ||
          lookahead == '|' ||
          lookahead == '}') ADVANCE(23);
      if (lookahead != 0) ADVANCE(22);
      END_STATE();
    case 11:
      if (eof) ADVANCE(12);
      if (lookahead == '.') ADVANCE(21);
      if (lookahead == '<') ADVANCE(36);
      if (lookahead == '@') ADVANCE(27);
      if (lookahead == '[') ADVANCE(30);
      if (lookahead == '\\') ADVANCE(24);
      if (lookahead == '{') ADVANCE(25);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(20);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(16);
      if (('#' <= lookahead && lookahead <= '&') ||
          lookahead == '*' ||
          lookahead == '+' ||
          lookahead == '/' ||
          lookahead == '=' ||
          lookahead == '>' ||
          (']' <= lookahead && lookahead <= '`') ||
          lookahead == '|' ||
          lookahead == '}') ADVANCE(23);
      if (lookahead != 0) ADVANCE(22);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_BQUOTE);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(aux_sym_escape_sequence_token1);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(aux_sym_number_token1);
      if (lookahead == '.') ADVANCE(7);
      if (lookahead == ':') ADVANCE(8);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(16);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(aux_sym_number_token2);
      if (lookahead == '.' ||
          lookahead == ':') ADVANCE(8);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(17);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(aux_sym_number_token3);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(18);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(aux_sym_number_token4);
      if (lookahead == '.' ||
          lookahead == ':') ADVANCE(8);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(19);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym__formal);
      if (lookahead == '.') ADVANCE(21);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(20);
      if (((!eof && set_contains(aux_sym_arg_value_token1_character_set_1, 9, lookahead)) ||
          lookahead == '"' ||
          lookahead == '\'') &&
          (lookahead < '#' || '&' < lookahead) &&
          lookahead != '*' &&
          lookahead != '+' &&
          (lookahead < '.' || '9' < lookahead) &&
          lookahead != '<' &&
          lookahead != '=' &&
          (lookahead < '[' || '_' < lookahead)) ADVANCE(22);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym__formal);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(18);
      if (lookahead != 0 &&
          (lookahead < '#' || '&' < lookahead) &&
          lookahead != '*' &&
          lookahead != '+' &&
          (lookahead < '/' || '9' < lookahead) &&
          (lookahead < '<' || '>' < lookahead) &&
          lookahead != '@' &&
          (lookahead < '[' || '`' < lookahead) &&
          (lookahead < '{' || '}' < lookahead)) ADVANCE(22);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym__formal);
      if (lookahead != 0 &&
          (lookahead < '#' || '&' < lookahead) &&
          lookahead != '*' &&
          lookahead != '+' &&
          (lookahead < '/' || '9' < lookahead) &&
          (lookahead < '<' || '>' < lookahead) &&
          lookahead != '@' &&
          (lookahead < '[' || '`' < lookahead) &&
          (lookahead < '{' || '}' < lookahead)) ADVANCE(22);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym__informal_misc);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym__informal_misc);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(15);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(aux_sym_path_token1);
      if (lookahead == '.') ADVANCE(9);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(29);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(aux_sym_lang_token1);
      if (lookahead == '-' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(aux_sym_lang_token1);
      if (lookahead == '-' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      if (lookahead != 0 &&
          lookahead != ']') ADVANCE(35);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_lang_invalid);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(34);
      if (lookahead == '-' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      if (lookahead != 0 &&
          lookahead != ']') ADVANCE(35);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_lang_invalid);
      if (lookahead != 0 &&
          lookahead != ']') ADVANCE(35);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '/') ADVANCE(38);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_LT_SLASH);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(aux_sym_arg_value_token1);
      if ((!eof && set_contains(aux_sym_arg_value_token1_character_set_1, 9, lookahead))) ADVANCE(40);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(aux_sym__quoted_string_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(42);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(43);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(aux_sym__quoted_string_token1);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(43);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(aux_sym__quoted_string_token2);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(45);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(46);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(aux_sym__quoted_string_token2);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(46);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(aux_sym__quoted_string_token3);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(47);
      if (lookahead != 0 &&
          lookahead != '`') ADVANCE(48);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(aux_sym__quoted_string_token3);
      if (lookahead != 0 &&
          lookahead != '`') ADVANCE(48);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 10},
  [2] = {.lex_state = 2},
  [3] = {.lex_state = 2},
  [4] = {.lex_state = 11},
  [5] = {.lex_state = 11},
  [6] = {.lex_state = 2},
  [7] = {.lex_state = 11},
  [8] = {.lex_state = 11},
  [9] = {.lex_state = 2},
  [10] = {.lex_state = 11},
  [11] = {.lex_state = 11},
  [12] = {.lex_state = 11},
  [13] = {.lex_state = 11},
  [14] = {.lex_state = 11},
  [15] = {.lex_state = 11},
  [16] = {.lex_state = 11},
  [17] = {.lex_state = 11},
  [18] = {.lex_state = 11},
  [19] = {.lex_state = 11},
  [20] = {.lex_state = 11},
  [21] = {.lex_state = 2},
  [22] = {.lex_state = 2},
  [23] = {.lex_state = 2},
  [24] = {.lex_state = 2},
  [25] = {.lex_state = 2},
  [26] = {.lex_state = 2},
  [27] = {.lex_state = 2},
  [28] = {.lex_state = 11},
  [29] = {.lex_state = 2},
  [30] = {.lex_state = 2},
  [31] = {.lex_state = 2},
  [32] = {.lex_state = 2},
  [33] = {.lex_state = 2},
  [34] = {.lex_state = 11},
  [35] = {.lex_state = 1},
  [36] = {.lex_state = 4},
  [37] = {.lex_state = 4},
  [38] = {.lex_state = 4},
  [39] = {.lex_state = 4},
  [40] = {.lex_state = 4},
  [41] = {.lex_state = 4},
  [42] = {.lex_state = 4},
  [43] = {.lex_state = 4},
  [44] = {.lex_state = 1},
  [45] = {.lex_state = 1},
  [46] = {.lex_state = 5},
  [47] = {.lex_state = 1},
  [48] = {.lex_state = 4},
  [49] = {.lex_state = 1},
  [50] = {.lex_state = 1},
  [51] = {.lex_state = 1},
  [52] = {.lex_state = 4},
  [53] = {.lex_state = 4},
  [54] = {.lex_state = 1},
  [55] = {.lex_state = 1},
  [56] = {.lex_state = 1},
  [57] = {.lex_state = 1},
  [58] = {.lex_state = 5},
  [59] = {.lex_state = 4},
  [60] = {.lex_state = 4},
  [61] = {.lex_state = 1},
  [62] = {.lex_state = 4},
  [63] = {.lex_state = 1},
  [64] = {.lex_state = 4},
  [65] = {.lex_state = 4},
  [66] = {.lex_state = 45},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 3},
  [70] = {.lex_state = 4},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 47},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 3},
  [76] = {.lex_state = 4},
  [77] = {.lex_state = 42},
  [78] = {.lex_state = 1},
  [79] = {.lex_state = 0, .external_lex_state = 1},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 3},
  [82] = {.lex_state = 1},
  [83] = {.lex_state = 0, .external_lex_state = 1},
  [84] = {.lex_state = 1},
  [85] = {.lex_state = 0, .external_lex_state = 1},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_BQUOTE] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [aux_sym_escape_sequence_token1] = ACTIONS(1),
    [aux_sym_number_token1] = ACTIONS(1),
    [aux_sym_number_token2] = ACTIONS(1),
    [aux_sym_number_token3] = ACTIONS(1),
    [aux_sym_number_token4] = ACTIONS(1),
    [sym__informal_misc] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [aux_sym_lang_token1] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [anon_sym_LT_SLASH] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [sym_expression_content] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_text] = STATE(68),
    [aux_sym__contents] = STATE(4),
    [sym_escape_sequence] = STATE(4),
    [sym_number] = STATE(14),
    [sym_pure] = STATE(4),
    [sym_informal] = STATE(10),
    [sym_expression] = STATE(4),
    [sym_path] = STATE(4),
    [sym_translation_marker] = STATE(4),
    [sym__tag] = STATE(4),
    [sym_tag_start] = STATE(4),
    [sym_tag_end] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_BQUOTE] = ACTIONS(5),
    [anon_sym_GT] = ACTIONS(7),
    [aux_sym_escape_sequence_token1] = ACTIONS(9),
    [aux_sym_number_token1] = ACTIONS(11),
    [aux_sym_number_token2] = ACTIONS(11),
    [aux_sym_number_token3] = ACTIONS(11),
    [aux_sym_number_token4] = ACTIONS(11),
    [sym__formal] = ACTIONS(13),
    [sym__informal_misc] = ACTIONS(15),
    [anon_sym_LBRACE] = ACTIONS(17),
    [anon_sym_AT] = ACTIONS(19),
    [anon_sym_LBRACK] = ACTIONS(21),
    [anon_sym_LT] = ACTIONS(23),
    [anon_sym_LT_SLASH] = ACTIONS(25),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 13,
    ACTIONS(27), 1,
      anon_sym_BQUOTE,
    ACTIONS(29), 1,
      aux_sym_escape_sequence_token1,
    ACTIONS(33), 1,
      sym__formal,
    ACTIONS(35), 1,
      sym__informal_misc,
    ACTIONS(37), 1,
      anon_sym_LBRACE,
    ACTIONS(39), 1,
      anon_sym_AT,
    ACTIONS(41), 1,
      anon_sym_LBRACK,
    ACTIONS(43), 1,
      anon_sym_LT,
    ACTIONS(45), 1,
      anon_sym_LT_SLASH,
    STATE(23), 1,
      sym_informal,
    STATE(24), 1,
      sym_number,
    ACTIONS(31), 4,
      aux_sym_number_token1,
      aux_sym_number_token2,
      aux_sym_number_token3,
      aux_sym_number_token4,
    STATE(3), 9,
      aux_sym__contents,
      sym_escape_sequence,
      sym_pure,
      sym_expression,
      sym_path,
      sym_translation_marker,
      sym__tag,
      sym_tag_start,
      sym_tag_end,
  [51] = 13,
    ACTIONS(29), 1,
      aux_sym_escape_sequence_token1,
    ACTIONS(33), 1,
      sym__formal,
    ACTIONS(35), 1,
      sym__informal_misc,
    ACTIONS(37), 1,
      anon_sym_LBRACE,
    ACTIONS(39), 1,
      anon_sym_AT,
    ACTIONS(41), 1,
      anon_sym_LBRACK,
    ACTIONS(43), 1,
      anon_sym_LT,
    ACTIONS(45), 1,
      anon_sym_LT_SLASH,
    ACTIONS(47), 1,
      anon_sym_BQUOTE,
    STATE(23), 1,
      sym_informal,
    STATE(24), 1,
      sym_number,
    ACTIONS(31), 4,
      aux_sym_number_token1,
      aux_sym_number_token2,
      aux_sym_number_token3,
      aux_sym_number_token4,
    STATE(6), 9,
      aux_sym__contents,
      sym_escape_sequence,
      sym_pure,
      sym_expression,
      sym_path,
      sym_translation_marker,
      sym__tag,
      sym_tag_start,
      sym_tag_end,
  [102] = 13,
    ACTIONS(9), 1,
      aux_sym_escape_sequence_token1,
    ACTIONS(13), 1,
      sym__formal,
    ACTIONS(15), 1,
      sym__informal_misc,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_AT,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(23), 1,
      anon_sym_LT,
    ACTIONS(25), 1,
      anon_sym_LT_SLASH,
    ACTIONS(49), 1,
      ts_builtin_sym_end,
    STATE(10), 1,
      sym_informal,
    STATE(14), 1,
      sym_number,
    ACTIONS(11), 4,
      aux_sym_number_token1,
      aux_sym_number_token2,
      aux_sym_number_token3,
      aux_sym_number_token4,
    STATE(5), 9,
      aux_sym__contents,
      sym_escape_sequence,
      sym_pure,
      sym_expression,
      sym_path,
      sym_translation_marker,
      sym__tag,
      sym_tag_start,
      sym_tag_end,
  [153] = 13,
    ACTIONS(51), 1,
      ts_builtin_sym_end,
    ACTIONS(53), 1,
      aux_sym_escape_sequence_token1,
    ACTIONS(59), 1,
      sym__formal,
    ACTIONS(62), 1,
      sym__informal_misc,
    ACTIONS(65), 1,
      anon_sym_LBRACE,
    ACTIONS(68), 1,
      anon_sym_AT,
    ACTIONS(71), 1,
      anon_sym_LBRACK,
    ACTIONS(74), 1,
      anon_sym_LT,
    ACTIONS(77), 1,
      anon_sym_LT_SLASH,
    STATE(10), 1,
      sym_informal,
    STATE(14), 1,
      sym_number,
    ACTIONS(56), 4,
      aux_sym_number_token1,
      aux_sym_number_token2,
      aux_sym_number_token3,
      aux_sym_number_token4,
    STATE(5), 9,
      aux_sym__contents,
      sym_escape_sequence,
      sym_pure,
      sym_expression,
      sym_path,
      sym_translation_marker,
      sym__tag,
      sym_tag_start,
      sym_tag_end,
  [204] = 13,
    ACTIONS(80), 1,
      anon_sym_BQUOTE,
    ACTIONS(82), 1,
      aux_sym_escape_sequence_token1,
    ACTIONS(88), 1,
      sym__formal,
    ACTIONS(91), 1,
      sym__informal_misc,
    ACTIONS(94), 1,
      anon_sym_LBRACE,
    ACTIONS(97), 1,
      anon_sym_AT,
    ACTIONS(100), 1,
      anon_sym_LBRACK,
    ACTIONS(103), 1,
      anon_sym_LT,
    ACTIONS(106), 1,
      anon_sym_LT_SLASH,
    STATE(23), 1,
      sym_informal,
    STATE(24), 1,
      sym_number,
    ACTIONS(85), 4,
      aux_sym_number_token1,
      aux_sym_number_token2,
      aux_sym_number_token3,
      aux_sym_number_token4,
    STATE(6), 9,
      aux_sym__contents,
      sym_escape_sequence,
      sym_pure,
      sym_expression,
      sym_path,
      sym_translation_marker,
      sym__tag,
      sym_tag_start,
      sym_tag_end,
  [255] = 13,
    ACTIONS(9), 1,
      aux_sym_escape_sequence_token1,
    ACTIONS(13), 1,
      sym__formal,
    ACTIONS(15), 1,
      sym__informal_misc,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_AT,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(23), 1,
      anon_sym_LT,
    ACTIONS(25), 1,
      anon_sym_LT_SLASH,
    ACTIONS(49), 1,
      ts_builtin_sym_end,
    STATE(10), 1,
      sym_informal,
    STATE(14), 1,
      sym_number,
    ACTIONS(11), 4,
      aux_sym_number_token1,
      aux_sym_number_token2,
      aux_sym_number_token3,
      aux_sym_number_token4,
    STATE(8), 9,
      aux_sym__contents,
      sym_escape_sequence,
      sym_pure,
      sym_expression,
      sym_path,
      sym_translation_marker,
      sym__tag,
      sym_tag_start,
      sym_tag_end,
  [306] = 13,
    ACTIONS(9), 1,
      aux_sym_escape_sequence_token1,
    ACTIONS(13), 1,
      sym__formal,
    ACTIONS(15), 1,
      sym__informal_misc,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_AT,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(23), 1,
      anon_sym_LT,
    ACTIONS(25), 1,
      anon_sym_LT_SLASH,
    ACTIONS(109), 1,
      ts_builtin_sym_end,
    STATE(10), 1,
      sym_informal,
    STATE(14), 1,
      sym_number,
    ACTIONS(11), 4,
      aux_sym_number_token1,
      aux_sym_number_token2,
      aux_sym_number_token3,
      aux_sym_number_token4,
    STATE(5), 9,
      aux_sym__contents,
      sym_escape_sequence,
      sym_pure,
      sym_expression,
      sym_path,
      sym_translation_marker,
      sym__tag,
      sym_tag_start,
      sym_tag_end,
  [357] = 1,
    ACTIONS(111), 13,
      anon_sym_BQUOTE,
      aux_sym_escape_sequence_token1,
      aux_sym_number_token1,
      aux_sym_number_token2,
      aux_sym_number_token3,
      aux_sym_number_token4,
      sym__formal,
      sym__informal_misc,
      anon_sym_LBRACE,
      anon_sym_AT,
      anon_sym_LBRACK,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [373] = 2,
    ACTIONS(113), 1,
      ts_builtin_sym_end,
    ACTIONS(115), 12,
      aux_sym_escape_sequence_token1,
      aux_sym_number_token1,
      aux_sym_number_token2,
      aux_sym_number_token3,
      aux_sym_number_token4,
      sym__formal,
      sym__informal_misc,
      anon_sym_LBRACE,
      anon_sym_AT,
      anon_sym_LBRACK,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [391] = 2,
    ACTIONS(117), 1,
      ts_builtin_sym_end,
    ACTIONS(119), 12,
      aux_sym_escape_sequence_token1,
      aux_sym_number_token1,
      aux_sym_number_token2,
      aux_sym_number_token3,
      aux_sym_number_token4,
      sym__formal,
      sym__informal_misc,
      anon_sym_LBRACE,
      anon_sym_AT,
      anon_sym_LBRACK,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [409] = 2,
    ACTIONS(121), 1,
      ts_builtin_sym_end,
    ACTIONS(123), 12,
      aux_sym_escape_sequence_token1,
      aux_sym_number_token1,
      aux_sym_number_token2,
      aux_sym_number_token3,
      aux_sym_number_token4,
      sym__formal,
      sym__informal_misc,
      anon_sym_LBRACE,
      anon_sym_AT,
      anon_sym_LBRACK,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [427] = 2,
    ACTIONS(125), 1,
      ts_builtin_sym_end,
    ACTIONS(127), 12,
      aux_sym_escape_sequence_token1,
      aux_sym_number_token1,
      aux_sym_number_token2,
      aux_sym_number_token3,
      aux_sym_number_token4,
      sym__formal,
      sym__informal_misc,
      anon_sym_LBRACE,
      anon_sym_AT,
      anon_sym_LBRACK,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [445] = 2,
    ACTIONS(129), 1,
      ts_builtin_sym_end,
    ACTIONS(131), 12,
      aux_sym_escape_sequence_token1,
      aux_sym_number_token1,
      aux_sym_number_token2,
      aux_sym_number_token3,
      aux_sym_number_token4,
      sym__formal,
      sym__informal_misc,
      anon_sym_LBRACE,
      anon_sym_AT,
      anon_sym_LBRACK,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [463] = 2,
    ACTIONS(133), 1,
      ts_builtin_sym_end,
    ACTIONS(135), 12,
      aux_sym_escape_sequence_token1,
      aux_sym_number_token1,
      aux_sym_number_token2,
      aux_sym_number_token3,
      aux_sym_number_token4,
      sym__formal,
      sym__informal_misc,
      anon_sym_LBRACE,
      anon_sym_AT,
      anon_sym_LBRACK,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [481] = 2,
    ACTIONS(137), 1,
      ts_builtin_sym_end,
    ACTIONS(139), 12,
      aux_sym_escape_sequence_token1,
      aux_sym_number_token1,
      aux_sym_number_token2,
      aux_sym_number_token3,
      aux_sym_number_token4,
      sym__formal,
      sym__informal_misc,
      anon_sym_LBRACE,
      anon_sym_AT,
      anon_sym_LBRACK,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [499] = 2,
    ACTIONS(141), 1,
      ts_builtin_sym_end,
    ACTIONS(111), 12,
      aux_sym_escape_sequence_token1,
      aux_sym_number_token1,
      aux_sym_number_token2,
      aux_sym_number_token3,
      aux_sym_number_token4,
      sym__formal,
      sym__informal_misc,
      anon_sym_LBRACE,
      anon_sym_AT,
      anon_sym_LBRACK,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [517] = 2,
    ACTIONS(143), 1,
      ts_builtin_sym_end,
    ACTIONS(145), 12,
      aux_sym_escape_sequence_token1,
      aux_sym_number_token1,
      aux_sym_number_token2,
      aux_sym_number_token3,
      aux_sym_number_token4,
      sym__formal,
      sym__informal_misc,
      anon_sym_LBRACE,
      anon_sym_AT,
      anon_sym_LBRACK,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [535] = 2,
    ACTIONS(147), 1,
      ts_builtin_sym_end,
    ACTIONS(149), 12,
      aux_sym_escape_sequence_token1,
      aux_sym_number_token1,
      aux_sym_number_token2,
      aux_sym_number_token3,
      aux_sym_number_token4,
      sym__formal,
      sym__informal_misc,
      anon_sym_LBRACE,
      anon_sym_AT,
      anon_sym_LBRACK,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [553] = 2,
    ACTIONS(151), 1,
      ts_builtin_sym_end,
    ACTIONS(153), 12,
      aux_sym_escape_sequence_token1,
      aux_sym_number_token1,
      aux_sym_number_token2,
      aux_sym_number_token3,
      aux_sym_number_token4,
      sym__formal,
      sym__informal_misc,
      anon_sym_LBRACE,
      anon_sym_AT,
      anon_sym_LBRACK,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [571] = 1,
    ACTIONS(155), 13,
      anon_sym_BQUOTE,
      aux_sym_escape_sequence_token1,
      aux_sym_number_token1,
      aux_sym_number_token2,
      aux_sym_number_token3,
      aux_sym_number_token4,
      sym__formal,
      sym__informal_misc,
      anon_sym_LBRACE,
      anon_sym_AT,
      anon_sym_LBRACK,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [587] = 1,
    ACTIONS(157), 13,
      anon_sym_BQUOTE,
      aux_sym_escape_sequence_token1,
      aux_sym_number_token1,
      aux_sym_number_token2,
      aux_sym_number_token3,
      aux_sym_number_token4,
      sym__formal,
      sym__informal_misc,
      anon_sym_LBRACE,
      anon_sym_AT,
      anon_sym_LBRACK,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [603] = 1,
    ACTIONS(115), 13,
      anon_sym_BQUOTE,
      aux_sym_escape_sequence_token1,
      aux_sym_number_token1,
      aux_sym_number_token2,
      aux_sym_number_token3,
      aux_sym_number_token4,
      sym__formal,
      sym__informal_misc,
      anon_sym_LBRACE,
      anon_sym_AT,
      anon_sym_LBRACK,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [619] = 1,
    ACTIONS(131), 13,
      anon_sym_BQUOTE,
      aux_sym_escape_sequence_token1,
      aux_sym_number_token1,
      aux_sym_number_token2,
      aux_sym_number_token3,
      aux_sym_number_token4,
      sym__formal,
      sym__informal_misc,
      anon_sym_LBRACE,
      anon_sym_AT,
      anon_sym_LBRACK,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [635] = 1,
    ACTIONS(119), 13,
      anon_sym_BQUOTE,
      aux_sym_escape_sequence_token1,
      aux_sym_number_token1,
      aux_sym_number_token2,
      aux_sym_number_token3,
      aux_sym_number_token4,
      sym__formal,
      sym__informal_misc,
      anon_sym_LBRACE,
      anon_sym_AT,
      anon_sym_LBRACK,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [651] = 1,
    ACTIONS(123), 13,
      anon_sym_BQUOTE,
      aux_sym_escape_sequence_token1,
      aux_sym_number_token1,
      aux_sym_number_token2,
      aux_sym_number_token3,
      aux_sym_number_token4,
      sym__formal,
      sym__informal_misc,
      anon_sym_LBRACE,
      anon_sym_AT,
      anon_sym_LBRACK,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [667] = 1,
    ACTIONS(135), 13,
      anon_sym_BQUOTE,
      aux_sym_escape_sequence_token1,
      aux_sym_number_token1,
      aux_sym_number_token2,
      aux_sym_number_token3,
      aux_sym_number_token4,
      sym__formal,
      sym__informal_misc,
      anon_sym_LBRACE,
      anon_sym_AT,
      anon_sym_LBRACK,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [683] = 2,
    ACTIONS(159), 1,
      ts_builtin_sym_end,
    ACTIONS(155), 12,
      aux_sym_escape_sequence_token1,
      aux_sym_number_token1,
      aux_sym_number_token2,
      aux_sym_number_token3,
      aux_sym_number_token4,
      sym__formal,
      sym__informal_misc,
      anon_sym_LBRACE,
      anon_sym_AT,
      anon_sym_LBRACK,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [701] = 1,
    ACTIONS(127), 13,
      anon_sym_BQUOTE,
      aux_sym_escape_sequence_token1,
      aux_sym_number_token1,
      aux_sym_number_token2,
      aux_sym_number_token3,
      aux_sym_number_token4,
      sym__formal,
      sym__informal_misc,
      anon_sym_LBRACE,
      anon_sym_AT,
      anon_sym_LBRACK,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [717] = 1,
    ACTIONS(139), 13,
      anon_sym_BQUOTE,
      aux_sym_escape_sequence_token1,
      aux_sym_number_token1,
      aux_sym_number_token2,
      aux_sym_number_token3,
      aux_sym_number_token4,
      sym__formal,
      sym__informal_misc,
      anon_sym_LBRACE,
      anon_sym_AT,
      anon_sym_LBRACK,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [733] = 1,
    ACTIONS(149), 13,
      anon_sym_BQUOTE,
      aux_sym_escape_sequence_token1,
      aux_sym_number_token1,
      aux_sym_number_token2,
      aux_sym_number_token3,
      aux_sym_number_token4,
      sym__formal,
      sym__informal_misc,
      anon_sym_LBRACE,
      anon_sym_AT,
      anon_sym_LBRACK,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [749] = 1,
    ACTIONS(145), 13,
      anon_sym_BQUOTE,
      aux_sym_escape_sequence_token1,
      aux_sym_number_token1,
      aux_sym_number_token2,
      aux_sym_number_token3,
      aux_sym_number_token4,
      sym__formal,
      sym__informal_misc,
      anon_sym_LBRACE,
      anon_sym_AT,
      anon_sym_LBRACK,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [765] = 1,
    ACTIONS(153), 13,
      anon_sym_BQUOTE,
      aux_sym_escape_sequence_token1,
      aux_sym_number_token1,
      aux_sym_number_token2,
      aux_sym_number_token3,
      aux_sym_number_token4,
      sym__formal,
      sym__informal_misc,
      anon_sym_LBRACE,
      anon_sym_AT,
      anon_sym_LBRACK,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [781] = 2,
    ACTIONS(161), 1,
      ts_builtin_sym_end,
    ACTIONS(157), 12,
      aux_sym_escape_sequence_token1,
      aux_sym_number_token1,
      aux_sym_number_token2,
      aux_sym_number_token3,
      aux_sym_number_token4,
      sym__formal,
      sym__informal_misc,
      anon_sym_LBRACE,
      anon_sym_AT,
      anon_sym_LBRACK,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [799] = 8,
    ACTIONS(163), 1,
      anon_sym_BQUOTE,
    ACTIONS(165), 1,
      anon_sym_LBRACE,
    ACTIONS(167), 1,
      anon_sym_AT,
    ACTIONS(169), 1,
      aux_sym_arg_value_token1,
    ACTIONS(171), 1,
      anon_sym_SQUOTE,
    ACTIONS(173), 1,
      anon_sym_DQUOTE,
    STATE(43), 1,
      sym_arg_value,
    STATE(52), 3,
      sym_expression,
      sym_path,
      sym__quoted_string,
  [826] = 3,
    ACTIONS(177), 1,
      sym_identifier,
    ACTIONS(175), 2,
      anon_sym_GT,
      anon_sym_PIPE,
    STATE(38), 2,
      sym_arg,
      aux_sym_decor_repeat1,
  [838] = 3,
    ACTIONS(177), 1,
      sym_identifier,
    ACTIONS(179), 2,
      anon_sym_GT,
      anon_sym_PIPE,
    STATE(36), 2,
      sym_arg,
      aux_sym_decor_repeat1,
  [850] = 3,
    ACTIONS(183), 1,
      sym_identifier,
    ACTIONS(181), 2,
      anon_sym_GT,
      anon_sym_PIPE,
    STATE(38), 2,
      sym_arg,
      aux_sym_decor_repeat1,
  [862] = 2,
    ACTIONS(188), 1,
      anon_sym_EQ,
    ACTIONS(186), 3,
      anon_sym_GT,
      sym_identifier,
      anon_sym_PIPE,
  [871] = 4,
    ACTIONS(177), 1,
      sym_identifier,
    ACTIONS(190), 1,
      anon_sym_GT,
    STATE(37), 1,
      sym_arg,
    STATE(44), 1,
      sym_decor,
  [884] = 4,
    ACTIONS(177), 1,
      sym_identifier,
    ACTIONS(192), 1,
      anon_sym_GT,
    STATE(37), 1,
      sym_arg,
    STATE(54), 1,
      sym_decor,
  [897] = 1,
    ACTIONS(117), 3,
      anon_sym_GT,
      sym_identifier,
      anon_sym_PIPE,
  [903] = 1,
    ACTIONS(194), 3,
      anon_sym_GT,
      sym_identifier,
      anon_sym_PIPE,
  [909] = 3,
    ACTIONS(196), 1,
      anon_sym_GT,
    ACTIONS(198), 1,
      anon_sym_PIPE,
    STATE(50), 1,
      aux_sym_tag_start_repeat1,
  [919] = 3,
    ACTIONS(200), 1,
      anon_sym_GT,
    ACTIONS(202), 1,
      anon_sym_PIPE,
    STATE(45), 1,
      aux_sym_tag_start_repeat1,
  [929] = 3,
    ACTIONS(205), 1,
      aux_sym_lang_token1,
    ACTIONS(207), 1,
      sym_lang_invalid,
    STATE(65), 1,
      sym_lang,
  [939] = 3,
    ACTIONS(209), 1,
      anon_sym_GT,
    ACTIONS(211), 1,
      anon_sym_PIPE,
    STATE(47), 1,
      aux_sym_tag_end_repeat1,
  [949] = 1,
    ACTIONS(214), 3,
      anon_sym_GT,
      sym_identifier,
      anon_sym_PIPE,
  [955] = 3,
    ACTIONS(216), 1,
      anon_sym_GT,
    ACTIONS(218), 1,
      anon_sym_PIPE,
    STATE(51), 1,
      aux_sym_tag_end_repeat1,
  [965] = 3,
    ACTIONS(198), 1,
      anon_sym_PIPE,
    ACTIONS(220), 1,
      anon_sym_GT,
    STATE(45), 1,
      aux_sym_tag_start_repeat1,
  [975] = 3,
    ACTIONS(218), 1,
      anon_sym_PIPE,
    ACTIONS(222), 1,
      anon_sym_GT,
    STATE(47), 1,
      aux_sym_tag_end_repeat1,
  [985] = 1,
    ACTIONS(224), 3,
      anon_sym_GT,
      sym_identifier,
      anon_sym_PIPE,
  [991] = 1,
    ACTIONS(125), 3,
      anon_sym_GT,
      sym_identifier,
      anon_sym_PIPE,
  [997] = 3,
    ACTIONS(198), 1,
      anon_sym_PIPE,
    ACTIONS(226), 1,
      anon_sym_GT,
    STATE(56), 1,
      aux_sym_tag_start_repeat1,
  [1007] = 3,
    ACTIONS(218), 1,
      anon_sym_PIPE,
    ACTIONS(228), 1,
      anon_sym_GT,
    STATE(57), 1,
      aux_sym_tag_end_repeat1,
  [1017] = 3,
    ACTIONS(198), 1,
      anon_sym_PIPE,
    ACTIONS(230), 1,
      anon_sym_GT,
    STATE(45), 1,
      aux_sym_tag_start_repeat1,
  [1027] = 3,
    ACTIONS(218), 1,
      anon_sym_PIPE,
    ACTIONS(232), 1,
      anon_sym_GT,
    STATE(47), 1,
      aux_sym_tag_end_repeat1,
  [1037] = 3,
    ACTIONS(205), 1,
      aux_sym_lang_token1,
    ACTIONS(234), 1,
      sym_lang_invalid,
    STATE(76), 1,
      sym_lang,
  [1047] = 3,
    ACTIONS(177), 1,
      sym_identifier,
    STATE(37), 1,
      sym_arg,
    STATE(63), 1,
      sym_decor,
  [1057] = 2,
    ACTIONS(236), 1,
      anon_sym_GT,
    ACTIONS(238), 1,
      sym_identifier,
  [1064] = 1,
    ACTIONS(209), 2,
      anon_sym_GT,
      anon_sym_PIPE,
  [1069] = 2,
    ACTIONS(240), 1,
      anon_sym_GT,
    ACTIONS(242), 1,
      sym_identifier,
  [1076] = 1,
    ACTIONS(200), 2,
      anon_sym_GT,
      anon_sym_PIPE,
  [1081] = 1,
    ACTIONS(244), 1,
      anon_sym_RBRACK,
  [1085] = 1,
    ACTIONS(246), 1,
      anon_sym_RBRACK,
  [1089] = 1,
    ACTIONS(248), 1,
      aux_sym__quoted_string_token2,
  [1093] = 1,
    ACTIONS(109), 1,
      ts_builtin_sym_end,
  [1097] = 1,
    ACTIONS(250), 1,
      ts_builtin_sym_end,
  [1101] = 1,
    ACTIONS(252), 1,
      aux_sym_path_token1,
  [1105] = 1,
    ACTIONS(254), 1,
      sym_identifier,
  [1109] = 1,
    ACTIONS(256), 1,
      anon_sym_BQUOTE,
  [1113] = 1,
    ACTIONS(258), 1,
      aux_sym__quoted_string_token3,
  [1117] = 1,
    ACTIONS(256), 1,
      anon_sym_SQUOTE,
  [1121] = 1,
    ACTIONS(256), 1,
      anon_sym_DQUOTE,
  [1125] = 1,
    ACTIONS(260), 1,
      aux_sym_path_token1,
  [1129] = 1,
    ACTIONS(262), 1,
      anon_sym_RBRACK,
  [1133] = 1,
    ACTIONS(264), 1,
      aux_sym__quoted_string_token1,
  [1137] = 1,
    ACTIONS(266), 1,
      anon_sym_RBRACE,
  [1141] = 1,
    ACTIONS(268), 1,
      sym_expression_content,
  [1145] = 1,
    ACTIONS(270), 1,
      ts_builtin_sym_end,
  [1149] = 1,
    ACTIONS(272), 1,
      aux_sym_path_token1,
  [1153] = 1,
    ACTIONS(274), 1,
      anon_sym_RBRACE,
  [1157] = 1,
    ACTIONS(276), 1,
      sym_expression_content,
  [1161] = 1,
    ACTIONS(278), 1,
      anon_sym_RBRACE,
  [1165] = 1,
    ACTIONS(280), 1,
      sym_expression_content,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 51,
  [SMALL_STATE(4)] = 102,
  [SMALL_STATE(5)] = 153,
  [SMALL_STATE(6)] = 204,
  [SMALL_STATE(7)] = 255,
  [SMALL_STATE(8)] = 306,
  [SMALL_STATE(9)] = 357,
  [SMALL_STATE(10)] = 373,
  [SMALL_STATE(11)] = 391,
  [SMALL_STATE(12)] = 409,
  [SMALL_STATE(13)] = 427,
  [SMALL_STATE(14)] = 445,
  [SMALL_STATE(15)] = 463,
  [SMALL_STATE(16)] = 481,
  [SMALL_STATE(17)] = 499,
  [SMALL_STATE(18)] = 517,
  [SMALL_STATE(19)] = 535,
  [SMALL_STATE(20)] = 553,
  [SMALL_STATE(21)] = 571,
  [SMALL_STATE(22)] = 587,
  [SMALL_STATE(23)] = 603,
  [SMALL_STATE(24)] = 619,
  [SMALL_STATE(25)] = 635,
  [SMALL_STATE(26)] = 651,
  [SMALL_STATE(27)] = 667,
  [SMALL_STATE(28)] = 683,
  [SMALL_STATE(29)] = 701,
  [SMALL_STATE(30)] = 717,
  [SMALL_STATE(31)] = 733,
  [SMALL_STATE(32)] = 749,
  [SMALL_STATE(33)] = 765,
  [SMALL_STATE(34)] = 781,
  [SMALL_STATE(35)] = 799,
  [SMALL_STATE(36)] = 826,
  [SMALL_STATE(37)] = 838,
  [SMALL_STATE(38)] = 850,
  [SMALL_STATE(39)] = 862,
  [SMALL_STATE(40)] = 871,
  [SMALL_STATE(41)] = 884,
  [SMALL_STATE(42)] = 897,
  [SMALL_STATE(43)] = 903,
  [SMALL_STATE(44)] = 909,
  [SMALL_STATE(45)] = 919,
  [SMALL_STATE(46)] = 929,
  [SMALL_STATE(47)] = 939,
  [SMALL_STATE(48)] = 949,
  [SMALL_STATE(49)] = 955,
  [SMALL_STATE(50)] = 965,
  [SMALL_STATE(51)] = 975,
  [SMALL_STATE(52)] = 985,
  [SMALL_STATE(53)] = 991,
  [SMALL_STATE(54)] = 997,
  [SMALL_STATE(55)] = 1007,
  [SMALL_STATE(56)] = 1017,
  [SMALL_STATE(57)] = 1027,
  [SMALL_STATE(58)] = 1037,
  [SMALL_STATE(59)] = 1047,
  [SMALL_STATE(60)] = 1057,
  [SMALL_STATE(61)] = 1064,
  [SMALL_STATE(62)] = 1069,
  [SMALL_STATE(63)] = 1076,
  [SMALL_STATE(64)] = 1081,
  [SMALL_STATE(65)] = 1085,
  [SMALL_STATE(66)] = 1089,
  [SMALL_STATE(67)] = 1093,
  [SMALL_STATE(68)] = 1097,
  [SMALL_STATE(69)] = 1101,
  [SMALL_STATE(70)] = 1105,
  [SMALL_STATE(71)] = 1109,
  [SMALL_STATE(72)] = 1113,
  [SMALL_STATE(73)] = 1117,
  [SMALL_STATE(74)] = 1121,
  [SMALL_STATE(75)] = 1125,
  [SMALL_STATE(76)] = 1129,
  [SMALL_STATE(77)] = 1133,
  [SMALL_STATE(78)] = 1137,
  [SMALL_STATE(79)] = 1141,
  [SMALL_STATE(80)] = 1145,
  [SMALL_STATE(81)] = 1149,
  [SMALL_STATE(82)] = 1153,
  [SMALL_STATE(83)] = 1157,
  [SMALL_STATE(84)] = 1161,
  [SMALL_STATE(85)] = 1165,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_text, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(79),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(69),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(60),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(67),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [37] = {.entry = {.count = 1, .reusable = false}}, SHIFT(83),
  [39] = {.entry = {.count = 1, .reusable = false}}, SHIFT(75),
  [41] = {.entry = {.count = 1, .reusable = false}}, SHIFT(58),
  [43] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [45] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [47] = {.entry = {.count = 1, .reusable = false}}, SHIFT(80),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_text, 1, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__contents, 2, 0, 0),
  [53] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__contents, 2, 0, 0), SHIFT_REPEAT(28),
  [56] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__contents, 2, 0, 0), SHIFT_REPEAT(34),
  [59] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__contents, 2, 0, 0), SHIFT_REPEAT(10),
  [62] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__contents, 2, 0, 0), SHIFT_REPEAT(14),
  [65] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__contents, 2, 0, 0), SHIFT_REPEAT(79),
  [68] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__contents, 2, 0, 0), SHIFT_REPEAT(69),
  [71] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__contents, 2, 0, 0), SHIFT_REPEAT(46),
  [74] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__contents, 2, 0, 0), SHIFT_REPEAT(40),
  [77] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__contents, 2, 0, 0), SHIFT_REPEAT(60),
  [80] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__contents, 2, 0, 0),
  [82] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__contents, 2, 0, 0), SHIFT_REPEAT(21),
  [85] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__contents, 2, 0, 0), SHIFT_REPEAT(22),
  [88] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__contents, 2, 0, 0), SHIFT_REPEAT(23),
  [91] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__contents, 2, 0, 0), SHIFT_REPEAT(24),
  [94] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__contents, 2, 0, 0), SHIFT_REPEAT(83),
  [97] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__contents, 2, 0, 0), SHIFT_REPEAT(75),
  [100] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__contents, 2, 0, 0), SHIFT_REPEAT(58),
  [103] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__contents, 2, 0, 0), SHIFT_REPEAT(41),
  [106] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__contents, 2, 0, 0), SHIFT_REPEAT(62),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_text, 2, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_translation_marker, 3, 0, 0),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pure, 1, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_pure, 1, 0, 0),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_path, 2, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_path, 2, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag_start, 2, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag_start, 2, 0, 0),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 3, 0, 0),
  [127] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 3, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_informal, 1, 0, 0),
  [131] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_informal, 1, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag_end, 2, 0, 0),
  [135] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag_end, 2, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag_start, 3, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag_start, 3, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_translation_marker, 3, 0, 0),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag_end, 3, 0, 0),
  [145] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag_end, 3, 0, 0),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag_start, 4, 0, 0),
  [149] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag_start, 4, 0, 0),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag_end, 4, 0, 0),
  [153] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag_end, 4, 0, 0),
  [155] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_escape_sequence, 1, 0, 0),
  [157] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_number, 1, 0, 0),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_escape_sequence, 1, 0, 0),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_number, 1, 0, 0),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [175] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_decor, 2, 0, 0),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [179] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_decor, 1, 0, 0),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_decor_repeat1, 2, 0, 0),
  [183] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_decor_repeat1, 2, 0, 0), SHIFT_REPEAT(39),
  [186] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arg, 1, 0, 0),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [194] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arg, 3, 0, 0),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [200] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_tag_start_repeat1, 2, 0, 0),
  [202] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tag_start_repeat1, 2, 0, 0), SHIFT_REPEAT(59),
  [205] = {.entry = {.count = 1, .reusable = false}}, SHIFT(64),
  [207] = {.entry = {.count = 1, .reusable = false}}, SHIFT(65),
  [209] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_tag_end_repeat1, 2, 0, 0),
  [211] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tag_end_repeat1, 2, 0, 0), SHIFT_REPEAT(70),
  [214] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__quoted_string, 3, 0, 0),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [224] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arg_value, 1, 0, 0),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [234] = {.entry = {.count = 1, .reusable = false}}, SHIFT(76),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [244] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_lang, 1, 0, 0),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [250] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [258] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [260] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [262] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [264] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [266] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [270] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_text, 3, 0, 0),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [274] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [276] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [278] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [280] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token_expression_content = 0,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token_expression_content] = sym_expression_content,
};

static const bool ts_external_scanner_states[2][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token_expression_content] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_penny_dialog_external_scanner_create(void);
void tree_sitter_penny_dialog_external_scanner_destroy(void *);
bool tree_sitter_penny_dialog_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_penny_dialog_external_scanner_serialize(void *, char *);
void tree_sitter_penny_dialog_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_penny_dialog(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_penny_dialog_external_scanner_create,
      tree_sitter_penny_dialog_external_scanner_destroy,
      tree_sitter_penny_dialog_external_scanner_scan,
      tree_sitter_penny_dialog_external_scanner_serialize,
      tree_sitter_penny_dialog_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
    .name = "penny_dialog",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
